const ProductCarddata = [
  {
    id: 1,
    img: "/assets/img/product-image1.jpg",
    description:
      "تلویزیون دوو با امکان پخش با گوشی و اتصال به یوتیوب و فضا های مجازی و FullHD",
    title: "Devvo television",
    price: `3,175,000`,
    discount: `4,200,000`,
    likes: 2500,
    information: "Apple iPhone XR 128GB Mobile Phone",
    discountpersent: 50,
  },
  {
    id: 2,
    img: "/assets/img/product-image2.jpg",
    description:
      "تلویزیون دوو با امکان پخش با گوشی و اتصال به یوتیوب و فضا های مجازی و FullHD",
    title: "",
    price: `3,175,000`,
    discount: `4,200,000`,
    likes: 2500,
    information: "Apple iPhone XR 128GB Mobile Phone",
    discountpersent: 50,
  },
  {
    id: 3,
    img: "/assets/img/product-image3.jpg",
    description:
      "تلویزیون دوو با امکان پخش با گوشی و اتصال به یوتیوب و فضا های مجازی و FullHD",
    title: "",
    price: `3,175,000`,
    discount: `4,200,000`,
    likes: 2500,
    information: "Apple iPhone XR 128GB Mobile Phone",
    discountpersent: 50,
  },
  {
    id: 4,
    img: "/assets/img/product-image4.jpg",
    description:
      "تلویزیون دوو با امکان پخش با گوشی و اتصال به یوتیوب و فضا های مجازی و FullHD",
    title: "",
    price: `3,175,000`,
    discount: `4,200,000`,
    likes: 2500,
    information: "Apple iPhone XR 128GB Mobile Phone",
    discountpersent: 50,
  },
  {
    id: 5,
    img: "/assets/img/television1.jpg",
    description: `گوشی موبایل ناتینگ مدل Phone 2a دو سیم کارت ظرفیت 256 گیگابایت رم 12 گیگابایت`,
    title: "",
    price: `3,175,000`,
    discount: `4,200,000`,
    likes: 2500,
    information: "Apple iPhone XR 128GB Mobile Phone",
    discountpersent: 50,
  },
  {
    id: 6,
    img: "/assets/img/television2.jpg",
    description: `گوشی موبایل ناتینگ مدل Phone 2a دو سیم کارت ظرفیت 256 گیگابایت رم 12 گیگابایت`,
    title: "",
    price: `3,175,000`,
    discount: `4,200,000`,
    likes: 2500,
    information: "Apple iPhone XR 128GB Mobile Phone",
    discountpersent: 50,
  },
  {
    id: 7,
    img: "/assets/img/television3.jpg",
    description: `گوشی موبایل ناتینگ مدل Phone 2a دو سیم کارت ظرفیت 256 گیگابایت رم 12 گیگابایت`,
    title: "",
    price: `3,175,000`,
    discount: `4,200,000`,
    likes: 2500,
    information: "Apple iPhone XR 128GB Mobile Phone",
    discountpersent: 50,
  },
  {
    id: 8,
    img: "/assets/img/television4.jpg",
    description: `گوشی موبایل ناتینگ مدل Phone 2a دو سیم کارت ظرفیت 256 گیگابایت رم 12 گیگابایت`,
    title: "",
    price: `3,175,000`,
    discount: `4,200,000`,
    likes: 2500,
    information: "Apple iPhone XR 128GB Mobile Phone",
    discountpersent: 50,
  },
];

export default ProductCarddata;
