const Discountdata = [
  {
    id: 1,
    img: "/assets/img/product-image-1.png",
    alt: "product-img-1",
    discount: 15,
    price: 170_000,
    title: "تیشرت مردانه",
  },
  {
    id: 2,
    img: "/assets/img/product-image-2.png",
    alt: "product-img-2",
    discount: 25,
    price: 250_000,
    title: "تیشرت مردانه",
  },
  {
    id: 3,
    img: "/assets/img/product-image-3.png",
    alt: "product-img-3",
    discount: 17,
    price: 340_000,
    title: "تیشرت مردانه",
  },
  {
    id: 4,
    img: "/assets/img/product-image-4.png",
    alt: "product-img-4",
    discount: 19,
    price: 180_000,
    title: "پیراهن مردانه",
  },
  {
    id: 5,
    img: "/assets/img/product-image-5.png",
    alt: "product-img-5",
    discount: 8,
    price: 190_000,
    title: "پیراهن صورتی",
  },
  {
    id: 6,
    img: "/assets/img/product-image-6.png",
    alt: "product-img-6",
    discount: 5,
    price: 110_000,
    title: "هودی ها رنگی",
  },
  {
    id: 7,
    img: "/assets/img/product-image-7.png",
    alt: "product-img-7",
    discount: 35,
    price: 70_000,
    title: "هودی های رنگی",
  },
  {
    id: 8,
    img: "/assets/img/product-image-11.png",
    alt: "product-img-8",
    discount: 4,
    price: 80_000,
    title: "شلوار جین",
  },
  {
    id: 9,
    img: "/assets/img/product-image-12.jpg",
    alt: "product-img-9",
    discount: 14,
    price: 890_000,
    title: "شلوار یوگا",
  },
];

export default Discountdata;
